cask_args appdir: "/Applications"

tap "homebrew/cask-fonts"
tap "heroku/brew"

brew "awscli"
brew "bundler-completion"
brew "curl"
brew "django-completion"
brew "docker"
brew "docker-compose"
brew "wget"
brew "git"
brew "git-flow"
brew "git-lfs"
brew "b4b4r07/tap/gomi"
brew "lv"
brew "goenv"
brew "jq"
brew "openssl"
brew "mysql-client"
brew "pyenv"
brew "rbenv"
brew "nodenv"
brew "node-build"
brew "terminal-notifier"
brew "tmux"
brew "tree"
brew "thefuck"
brew "the_silver_searcher"
brew "reattach-to-user-namespace"
brew "vim"
brew "tig"
brew "zsh"
brew "zplug"
brew "zsh-syntax-highlighting"
brew "zsh-history-substring-search"
brew "zsh-navigation-tools"
brew "zsh-autosuggestions"
brew "mas"
brew "htop"
brew "nkf"
brew "lua"
brew "editorconfig"
brew "peco"
brew "kitchen-completion"
brew "ruby-completion"
brew "gem-completion"
brew "rake-completion"
brew "rails-completion"
brew "grunt-completion"
brew "pip-completion"
brew "php"
brew "composer"
brew "nginx"
brew "dnsmasq"
brew "mysql-client"
brew "mysql", version: "5.7"
brew "maven"
brew "postgresql"
brew "heroku"
brew "redis"
brew "translate-shell"
brew "gh"
brew "deno"

# cask
cask "1password"
cask "alfred"
cask "adobe-creative-cloud"
cask "appcleaner"
cask "android-studio"
cask "bettertouchtool"
cask "bitwarden"
cask "chrome-remote-desktop-host"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "gyazo"
cask "iterm2"
cask "visual-studio-code"
cask "slack"
cask "sequel-pro"
cask "sketch"
cask "townwifi"
cask "vivaldi"
cask "macs-fan-control"
cask "the-unarchiver"
cask "r"
cask "rstudio"
cask "bartender"
cask "viber"
cask "xmind"
cask "discord"
cask "figma"
cask "zoomus"
cask "karabiner-elements"
cask "jasper"
cask "notion"
cask "menumeters"

# fonts
cask "font-fontawesome"
cask "font-ricty-diminished"
cask "font-noto-sans-cjk"
cask "font-hack-nerd-font"
cask "font-hasklig"

# mac app store
mas "Spark", id: 1176895641
mas "LINE", id: 539883307
mas "Forklift", id: 412448059
mas "Kindle", id: 405399194
mas "Xcode", id: 497799835
mas "TweetDeck by Twitter", id: 485812721
